image: node:latest

cache:
  paths:
    - node_modules/

before_script:
  - npm install
  - npm install -g @angular/cli

stages:
  - pages

pages:
  stage: pages
  environment:
    name: production
  script:
    - ng build --prod --output-path=public --base-href /frontend/
  only:
    - master
  artifacts:
    paths:
      - public